### ISSUE TITLE
Option to set default kernel

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#11]
Have a command line option `--default-language` that sets the default kernel to spawn if a request for a kernel (POST) does not explicitly state a kernel language name.

**Comment by nitind** [comment]
I'll take this one.

**Comment by parente** [comment]
@nitind Cool. Let me know if you want to pair on it or have an early PR for comments.

**Comment by parente** [comment]
How's this one coming along? I'm hoping #9 and #10 go into master today. Then this is the last one I think worth having before cutting a 0.1.0 release.

**Comment by nitind** [comment]
I'm overriding the get_json_body method in our services.kernels.MainKernelHandler so we can avoid reimplementing the original handler's entire post() method, but our handler still needs to get the new default kernel name from an environment variable. I'd hoped to not do it in that file, but that looks to be the simplest.
