### ISSUE TITLE
Support dev/test on Python 2.7

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#22]
The project supports Python 2.7, but we haven't setup the automation to run the tests against 2.7. They started failing with strange exceptions on travis in PR #21. So we disabled the 2.7 test env in that PR until we can get a 2.7 test environment running locally to debug.

**Comment by nitind** [comment]
A local docker image reproducing the failures can be created from the original jupyter/minimal-notebook Dockerfile, replacing python-dev with python2.7-dev and the Python 3 Miniconda3-3.9.1-Linux-x86_64.sh with the Python 2 Miniconda-3.9.1-Linux-x86_64.sh .

**Comment by parente** [comment]
We could also just switch to using the jupyter/scipy-notebook image which has python2 installed already and then adopt the same approach used in the dashboards Makefile for running tests against 2 and 3.

**Comment by parente** [comment]
Fixed by PR #33
