### ISSUE TITLE
Option to enable kernel list

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#23]
Getting a list of all running kernel IDs should be considered an admin capability in many scenarios. The server should default to *not* supporting `GET /api/kernels` (conservative, more secure). If the user specifies `--KernelGatewayApp.list_kernels` on gateway start, the server should expose the endpoint.

**Comment by nitind** [comment]
I'll handle this.

**Comment by nitind** [comment]
@parente I've updated the help text.

**Comment by parente** [comment]
Fixed by associated PR.
