### ISSUE TITLE
README section about how to use microservices feature

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#37]
* [ ] update description at the top, it's not just providing the jupyter API and websockets anymore
* [ ] new bullet in "what it provides" about 
* [ ] new section with more info about the notebook-http mode
* [ ] link to github view of the api_intro notebook in that section
* [ ] document the `make` command structure for running with one of the notebooks in `etc` like: 

```
make dev ARGS="--KernelGatewayApp.api='notebook-http' \
--KernelGatewayApp.seed_uri=/srv/kernel_gateway/etc/api_examples/scotch_api.ipynb"
```

**Comment by Lull3rSkat3r** [comment]
Grabbing this.

**Comment by parente** [comment]
Great. Thanks!
