### ISSUE TITLE
Support lightweight request distribution for notebook-http mode

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#38]
* [x] don't hardcode 1 kernel to spawn on start, respect the `prespawn_count` parameter
* [x] on every request, round-robin through the list of kernels
* [x] make communication with a given kernel asynchronous to avoid blocking the tornado handling of other incoming requests but ensure the kernel remains "locked" from use by other requests until the current request is fully handled (hard)

Use case: want to deploy a single container with kernel gateway and have it scale with a process pool for small to medium loads without the cost of scaling at the container level associated with handling much larger loads

**Comment by parente** [comment]
Pairing with @poplav

**Comment by poplav** [comment]
PR #41 will close this issue.
