### ISSUE TITLE
Move most of the examples in etc/ to kernel_gateway_demos

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#39]
If they're not needed for testing, they probably make more sense over in the demos repo. The README should get updated to point to the demos repo (e.g., the big client example should be removed from the README and links should be put in their place). Each demo in the kernel_gateway repo should be in a new subfolder in the `kernel_gateway_demos` repo.

**Comment by parente** [comment]
Should we move the rest of the api_examples too? Was that a miss?

**Comment by poplav** [comment]
My concern was the api_examples were being used at [the running section](https://github.com/jupyter-incubator/kernel_gateway#running).  Where the running section is the baseline example usage of the repository and the complete set of demos were linked below.  We could duplicate them in both repositories, I am just not sure if we would want to completely remove all even basic examples?

**Comment by parente** [comment]
Ah, I see it now. Let's get the scotch one out of here so we don't have to maintain it in two place and update the README not to refer to that one. But the other simple ones can stay for the reason you gave.
