### ISSUE TITLE
Option to expose notebook-http endpoints as swagger doc

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#42]
So developers know what's available.

* [x] well-known endpoint like `/_api/spec` or some such. (The underscore indicates this is a API provided by the kernel gateway itself, not the notebook, and putting it under spec indicates it's the specification for the API and leaves us room to expose other things under `/_api` in the future.)
* [x] endpoint just returns the swagger JSON, not a rendering of it (Render should be done by external tools.)

**Comment by Lull3rSkat3r** [comment]
PR #66 will close this
