### ISSUE TITLE
Pass HTTP Headers To Code Cells

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/kernel_gateway#45]
The headers from the HTTP request need to be passed along to the `REQUEST` object for cell execution. Things that need to be done:

* [x] Pass the headers through to the cell execution via `REQUEST`
* [x] Update the example notebooks to show access of headers
* [x] Update the documentation to document access of headers

**Comment by parente** [comment]
If you've got a use case to point at, please do.

**Comment by Lull3rSkat3r** [comment]
When implementing the Pet Store Swagger Spec, jupyter-incubator/kernel_gateway_demos#2, I need the ability to access the HTTP request headers for the content. This is needed because the Swagger Petstore API allows for response to be either JSON or xml.

**Comment by parente** [comment]
This one doesn't require discussion. Just pass through REQUEST as you said.
