### ISSUE TITLE
Cell Code Needs To Set HTTP Response Code

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/kernel_gateway#47]
When implementing the Pet Store Swagger Spec, jupyter-incubator/kernel_gateway_demos#2, I need the ability to set the status code for the HTTP response. This is needed because the Swagger Petstore API requires multiple statuses for requests. And in general this will be needed to provide mature and proper functionality to developers using the kernel gateway.

I have two ideas for how this could be implemented, but there may be more. I have highlighted these ideas in upyter-incubator/kernel_gateway#46 and listed the advantages and disadvantages, but will document the differences for this use case here.

# Implementation 1: Display Data
We can utilize display data to set the response status. An example in python would be: 

```python
# GET /foo/bar
from IPython import display
display.publish_display_data({
    'http-response/status' : 200
})
```

The only implementation needed in the kernel gateway would be to do the following:
  1. In the kernel gateway, check if there is an 'http-response/status' in the display data
  1. If there is, set the response status code in the tornado handler, otherwise default to our current strategy

# Implementation 2: Comm API
We can provide a comm channel API which will allow for objects to be created which will relay the response information to the kernel gateway. An example implementation could look like this:

```python
from KernelGateway import Response
# GET /foo/bar
Response('foo', status=200)
```

**Comment by parente** [comment]
Going to "merge" this into #46 and make that about arbitrary HTTP response metadata.
