### ISSUE TITLE
Optional /_api/source endpoint to download the original notebook for notebook-http mode

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#48]
What the title says.

Also, want to have a command line option with the default being “no, you can’t download the notebook".
Probably something like “—allow-notebook-download” or something.

**Comment by poplav** [comment]
PR [#59](https://github.com/jupyter-incubator/kernel_gateway/pull/59) should add the option --KernelGatewayApp.allow_notebook_download=True, but defaulting to False.

**Comment by parente** [comment]
Fixed by #59
