### ISSUE TITLE
Request Code is not properly interpreted by the Julia REPL

### ISSUE THREAD

**Issue by poplav** [jupyter-incubator/kernel_gateway#57]
The issue arises when using the kernel gateway in notebook-http mode using a Julia kernel.

In the [kernel_gateway/handler](https://github.com/jupyter-incubator/kernel_gateway/blob/master/kernel_gateway/services/notebooks/handlers.py#L95), request code is being executed before source code, where the source code is dependent on the execution of the request code.  The Julia REPL treats strings differently than the other kernels like R and Python.  Due to Julia treating strings differently the request code will not be properly assigned resulting in errors in the source code.  Specifically, Julia does not support ``` ' ``` for strings.  An example of the issue is apparent in the following files/comparisons of the REPLs.

![julia_r_python_repl_json](https://cloud.githubusercontent.com/assets/2311898/11965783/92bbee9e-a8bc-11e5-977c-f17765c07095.png)

![julia_string](https://cloud.githubusercontent.com/assets/2311898/11965785/97d20ab2-a8bc-11e5-8284-9c33739bff9f.png)

**Comment by parente** [comment]
Ah, yes. The JSON string assignment to REQUEST has to be made more language neutral or has to become a language map like the assignment operator is.

/cc @nitind @Lull3rSkat3r

**Comment by poplav** [comment]
PR [#58](https://github.com/jupyter-incubator/kernel_gateway/pull/58) should resolve this issue.  I tested the branch against the [Julia scotch notebook API] (https://github.com/poplav/kernel_gateway_demos/blob/issue-4-port-scotch-api/scotch_demo/notebooks/scotch_api_julia.ipynb) I was developing and it looks to work while not breaking anything else.
