### ISSUE TITLE
Pass Configuration Values To Notebook

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/kernel_gateway#76]
I am thinking about how you could configure an application in `notebook-http` mode. Initially, I think we could add a command line option, say `--KernelGatewatApp.custom=foo:bar`, which can generate a json string representing the config value. 

```json
{
  "foo" : "bar"
}
```

There could then be a config cell which will parse a variable called `CONFIG`, which is the json structure we defined. An example, in python, would be:

```python
# Config
configuration = json.loads(CONFIG)
print(configuration['foo'])
```

**Comment by Lull3rSkat3r** [comment]
Thought of this while daydreaming and wanted to dump here for conversation.

**Comment by parente** [comment]
Environment variables would pass through to the kernel with no extra work.

**Comment by parente** [comment]
I think we can close this.

```
export FOO='test'
jupyter kernelgateway
```

```
docker run -e FOO=test jupyter/minimal-kernel
```

In both cases, the environment variable `FOO` will be available to all kernels launched. The kernel can do whatever is appropriate for the kernel language to access them.
