### ISSUE TITLE
Installation does not complete in Windows / missing exe and script

### ISSUE THREAD

**Issue by ChristophLo** [jupyter-incubator/kernel_gateway#78]
I think something is broken with the jupyter gateway installation using Windows (if it is not and I am simply to clumsy to do it properly, please excuse this post and delete it...)

I am using Windows 10 with Anaconda& Python 2.7.
Following the "Try It" section on the website, I installed  jupyter gateway via  "pip install jupyter_kernel_gateway". 
When using "jupyter kernelgateway --help-all" to test the installation, I get the error message "'kernelgateway' is not a jupyter command".
It looks like that in Windows, each legit jupyter command has its own .exe file and matching  Python script - which kernelgateway has not. For me, pip install only installed the script, but with the wrong name ("jupyter-kernelgateway").

For solving this problem, I just copied the already existing "jupyter-notebook.exe" file (these files same to be identical for each command) and renamed it "jupyter-kernelgateway.exe", and renamed the existing script file "jupyter-kernelgateway" to "jupyter-kernelgateway-script.py".
Now, jupyter gateway works perfectly fine under Windows. 
I am not really sure if there is indeed something wrong with the current installation script, or if it is just my computer or my too limited python skills, but I hoped that this report is to any use for you guys...

**Comment by parente** [comment]
It's more likely than not our bug since we don't have good (any?) test coverage (manual or automated) on Windows.

I thought we were duplicating what the other jupyter projects do to install their bin scripts and make them accessible under the `jupyter <something>` command. But I suspect we're missing a step to make it work on Windows specifically. (They work fine on Linux and OS X.)

**Comment by parente** [comment]
Evidence: https://github.com/jupyter/nbconvert/blob/master/setup.py#L191

**Comment by parente** [comment]
@ChristophLo I think I've got the exe problem fixed for Windows, but I'm having a heck of a time getting a Windows VM setup to test it. If you're familiar with testing pull requests, it might speed things along if you could pull and try the one associated with this work item. If not, don't worry about it: I'll get it setup sooner or later.

**Comment by ChristophLo** [comment]
I'll try...

**Comment by ChristophLo** [comment]
The current fork bdist-wheel including the changes you made one hour ago does indeed install and de-install correctly in windows (deinstalled my old kernel-gateway, removed the files I created manually, installed via pip locally using the aforementioned fork which did indeed create the required .exe files, and deinstalled again which removed the .exe files).
So, the issue seems to be fixed.

**Comment by parente** [comment]
Awesome. Thanks for testing it so quickly! I'll get it merged.

**Comment by ChristophLo** [comment]
Thanks for fixing!
